CREATE DATABASE SPRING_MVC2_BOARD_ADVANCE;

USE SPRING_MVC2_BOARD_ADVANCE;

CREATE TABLE T_BOARD_ADVANCE(
	NUM  		INT NOT NULL PRIMARY KEY,
	WRITER 		VARCHAR(20),
	EMAIL 		VARCHAR(20),
	SUBJECT 	VARCHAR(50),
	PASSWORD 	VARCHAR(20),
	REG_DATE 	DATE,
	REF 		INT,             
	RE_STEP 	INT,     	  
	RE_LEVEL 	INT,		  
	READ_COUNT 	INT,
	CONTENT 	VARCHAR(20)
);

SELECT
		*
FROM
		T_BOARD_ADVANCE;